Interior.create(:klasse_id => Klasse.find_by_name('A').id, :code => '001', :desc => "ткань черная")
Interior.create(:klasse_id => Klasse.find_by_name('A').id, :code => '011', :desc => "ткань черная")
Interior.create(:klasse_id => Klasse.find_by_name('A').id, :code => '018', :desc => "ткань серый кристалл")
Interior.create(:klasse_id => Klasse.find_by_name('A').id, :code => '101', :desc => "искусственная кожа 'Артико' черная")
Interior.create(:klasse_id => Klasse.find_by_name('A').id, :code => '105', :desc => "искусственная кожа 'Артико' бежевая Сахара")
Interior.create(:klasse_id => Klasse.find_by_name('A').id, :code => '108', :desc => "искусственная кожа 'Артико' серый кристалл")
Interior.create(:klasse_id => Klasse.find_by_name('A').id, :code => '601', :desc => "ткань / искусственная кожа 'Артико' черная")
Interior.create(:klasse_id => Klasse.find_by_name('A').id, :code => '608', :desc => "ткань / искусственная кожа 'Артико' серый кристалл")
Interior.create(:klasse_id => Klasse.find_by_name('A').id, :code => '201', :desc => "кожа черная")
Interior.create(:klasse_id => Klasse.find_by_name('A').id, :code => '204', :desc => "кожа коричневый лесной орех")
Interior.create(:klasse_id => Klasse.find_by_name('A').id, :code => '208', :desc => "кожа серый кристалл")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '021', :desc => "ткань черная")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '028', :desc => "ткань серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '062', :desc => "ткань черная/ синий")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '065', :desc => "ткань черная/ бежевый")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '421', :desc => "ткань / искусственная кожа 'Артико' черная")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '425', :desc => "ткань / искусственная кожа 'Артико' бежевый миндаль")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '428', :desc => "ткань / искусственная кожа 'Артико' серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '721', :desc => "искусственная кожа 'Артико' черная")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '728', :desc => "искусственная кожа 'Артико' черная/ серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '121', :desc => "искусственная кожа 'Артико' черная")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '125', :desc => "искусственная кожа 'Артико' бежевый миндаль")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '128', :desc => "искусственная кожа 'Артико' серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '221', :desc => "кожа черная")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '224', :desc => "кожа черная/ капучино")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '225', :desc => "кожа бежевый миндаль")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '228', :desc => "кожа черная/ серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '235', :desc => "кожа черная/ бежевая сахара")
Interior.create(:klasse_id => Klasse.find_by_name('B').id, :code => '237', :desc => "кожа черная/ красный фламенко")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '001', :desc => "ткань черная")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '008', :desc => "ткань черная/ серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '401', :desc => "ткань черная")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '408', :desc => "ткань серый риф/ серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '701', :desc => "ткань / искусственная кожа 'Артико' черная")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '708', :desc => "ткань / искусственная кожа 'Артико' черная/ серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '101', :desc => "искусственная кожа 'Артико' черная")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '105', :desc => "искусственная кожа 'Артико' черная/ бежевый миндаль")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '105', :desc => "искусственная кожа 'Артико' коричневый мокко/ бежевый миндаль")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '108', :desc => "искусственная кожа 'Артико' черная/ серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '108', :desc => "искусственная кожа 'Артико' серый риф/ серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '201', :desc => "кожа черная")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '205', :desc => "кожа черная/ бежевый миндаль")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '205', :desc => "кожа коричневый мокко/ бежевый миндаль")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '208', :desc => "кожа черная/ серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '208', :desc => "кожа серый риф/ серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '254', :desc => "кожа черная/ каштановый")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '264',	:desc => "кожа черная/ натурально- бежевый")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '801',	:desc => "кожа- наппа черная")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '808',	:desc => "кожа- наппа серый риф/ серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => '001', :desc => "ткань черная")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => '701', :desc => "ткань / искусственная кожа 'Артико' черная")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => '704', :desc => "ткань / искусственная кожа 'Артико' бежевый миндаль")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => '708', :desc => "ткань / искусственная кожа 'Артико' серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => '101', :desc => "искусственная кожа 'Артико' черная")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => '104', :desc => "искусственная кожа 'Артико' бежевый миндаль")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => '201', :desc => "кожа черная")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => '204', :desc => "кожа бежевый миндаль")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => '205', :desc => "кожа бежевая сахара")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => '208', :desc => "кожа серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => 'X63', :desc => "кожа designo светло-коричневая, двухцветная")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => 'X89', :desc => "кожа designo 'кортечча', двухцветная'")
Interior.create(:klasse_id => Klasse.find_by_name('ML').id, :code => '001', :desc => "ткань / искусственная кожа 'Артико' черная")
Interior.create(:klasse_id => Klasse.find_by_name('ML').id, :code => '101', :desc => "искусственная кожа 'Артико' черная")
Interior.create(:klasse_id => Klasse.find_by_name('ML').id, :code => '105', :desc => "искусственная кожа 'Артико' бежевый миндаль")
Interior.create(:klasse_id => Klasse.find_by_name('ML').id, :code => '108', :desc => "искусственная кожа 'Артико' серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('ML').id, :code => '201', :desc => "кожа черная")
Interior.create(:klasse_id => Klasse.find_by_name('ML').id, :code => '205', :desc => "кожа бежевый миндаль")
Interior.create(:klasse_id => Klasse.find_by_name('ML').id, :code => '208', :desc => "кожа серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('ML').id, :code => '254', :desc => "кожа черная/ коричневый тобакко")
Interior.create(:klasse_id => Klasse.find_by_name('ML').id, :code => '255', :desc => "кожа черная/ бежевый миндаль")
Interior.create(:klasse_id => Klasse.find_by_name('ML').id, :code => '258', :desc => "кожа черная/ серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '151', :desc => "искусственная кожа 'Артико' черная")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '154', :desc => "искусственная кожа 'Артико' бежевый кашемир")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '158', :desc => "искусственная кожа 'Артико' серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '221', :desc => "искусственная кожа 'Артико' черная")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '224', :desc => "искусственная кожа 'Артико' бежевый кашемир")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '228', :desc => "искусственная кожа 'Артико' серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '264', :desc => "искусственная кожа 'Артико' чёрная/ бежевый кашемир")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '268', :desc => "искусственная кожа 'Артико' чёрная/ серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '511', :desc => "кожа- наппа черная")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '514', :desc => "кожа- наппа бежевый кашемир")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '518', :desc => "кожа- наппа серая альпака")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '011', :desc => "ткань чёрная/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '211',:desc => "кожа чёрная/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '214', :desc => "кожа бежевый кашемир/ бежевая саванна")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '218', :desc => "кожа серая альпака/ серый базальт")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '274', :desc => "кожа каштановая/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '275', :desc => "кожа бежевая сахара/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '821', :desc => "кожа 'Пассьон' чёрная/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '824', :desc => "кожа 'Пассьон' бежевый кашемир/ бежевая саванна")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '828', :desc => "кожа 'Пассьон' серая альпака/ серый базальт")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '884', :desc => "кожа 'Пассьон' каштановая/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '885', :desc => "кожа 'Пассьон' бежевая сахара/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '901', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' чёрная/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '904', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' бежевый кашемир/ бежевая саванна")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '908', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' серая альпака/ серый базальт")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '911', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' чёрная/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '914', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' бежевый кашемир/ бежевая саванна")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '918', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' серая альпака/ серый базальт")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '954', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' каштановая/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '955', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' бежевая сахара/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '964', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' каштановая/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('S').id, :code => '966', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' бежевая сахара/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('S').id,	:code => 'U09',	 :desc => "кожа 'Пассьон' пакет отделки кожей 'Пассьон'")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '211', :desc => "кожа чёрная/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '214', :desc => "кожа бежевый кашемир/ бежевая саванна")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '218', :desc => "кожа серая альпака/ серый базальт")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '265', :desc => "кожа бежевая сахара/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '267', :desc => "кожа баклажанная/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '811', :desc => "кожа 'Пассьон' чёрная/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '521', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' чёрная/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '531', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' чёрная/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '814', :desc => "кожа 'Пассьон' бежевый кашемир/ бежевая саванна")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '818', :desc => "кожа 'Пассьон' серая альпака/ серый базальт")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '524', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' бежевый кашемир/ бежевая саванна")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '534', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' бежевый кашемир/ бежевая саванна")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '528', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' серая альпака/ серый базальт")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '538', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' серая альпака/ серый базальт")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '575', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' бежевая сахара/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '865', :desc => "кожа 'Пассьон' бежевая сахара/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '867', :desc => "кожа 'Пассьон' баклажанная/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '567', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' баклажанная/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '577', :desc => "кожа 'Пассьон' пакет 'Эксклюзив' баклажанная/ чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('SLK').id, :code => '001', :desc => "ткань чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('SLK').id, :code => '201', :desc => "кожа чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('SLK').id, :code => '205', :desc => "кожа бежевая сахара")
Interior.create(:klasse_id => Klasse.find_by_name('SLK').id, :code => '208', :desc => "кожа серый кристалл")
Interior.create(:klasse_id => Klasse.find_by_name('SLK').id, :code => '801', :desc => "кожа- наппа чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('SLK').id, :code => '807', :desc => "кожа- наппа бенгальский красный")
Interior.create(:klasse_id => Klasse.find_by_name('SLK').id, :code => '854', :desc => "кожа- наппа коричневый орех")
Interior.create(:klasse_id => Klasse.find_by_name('SLK').id, :code => '501', :desc => "кожа- наппа 'Эксклюзив' чёрная")
Interior.create(:klasse_id => Klasse.find_by_name('SLK').id, :code => '507', :desc => "кожа- наппа 'Эксклюзив' бенгальский красный")

Interior.create(:klasse_id => Klasse.find_by_name('C').id, :code => '131', :desc => "искуственная кожа Artico черная с контрастной прострочкой 'фарфор'")
Interior.create(:klasse_id => Klasse.find_by_name('C').id, :code => '901', :desc => "искуственная кожа ARTICO/DINAMICA черная")
Interior.create(:klasse_id => Klasse.find_by_name('CL').id, :code => '521', :desc => "кожа Exclusive PASSION")
Interior.create(:klasse_id => Klasse.find_by_name('CLS').id, :code => '815', :desc => "кожа PASSION фарфоровая/черная")
Interior.create(:klasse_id => Klasse.find_by_name('CLS').id, :code => '811', :desc => "кожа PASSION  черная")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '601', :desc => "ткань DINAMICA / иск. кожа ARTICO")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '231', :desc => "кожа спорт черная")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '251', :desc => "кожа черная")
Interior.create(:klasse_id => Klasse.find_by_name('E').id, :code => '257', :desc => "кожа красная 'фламенко' / черная")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '275', :desc => "двухцветная кожа черная / фарфор с контрастной прострочкой")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '574', :desc => "двухцветная кожа Nappa черная / коричневая 'maron' с контрастной прострочкой")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '274', :desc => "двухцветная кожа черная / коричневая 'maron' с контрастной прострочкой")
Interior.create(:klasse_id => Klasse.find_by_name('GL').id, :code => '575', :desc => "двухцветная кожа Nappa черная / фарфор с контрастной прострочкой")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => '224', :desc => "кожа 'коричневый мокко'")
Interior.create(:klasse_id => Klasse.find_by_name('GLK').id, :code => '128', :desc => "искуственная кожа ARTICO 'Серая альпака'")





